// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xLo6WE7nN3YeCEb-yNgzVdDxRhoUFXA',
    appId: '1:287867991282:web:c64a1aa84fc9f039ab0c6b',
    messagingSenderId: '287867991282',
    projectId: 'aptnote',
    authDomain: 'aptnote.firebaseapp.com',
    storageBucket: 'aptnote.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GgdrNcXPNN2H43AiQ3ellmXMJBhNIJA',
    appId: '1:287867991282:android:c71f10c1eaa5150fab0c6b',
    messagingSenderId: '287867991282',
    projectId: 'aptnote',
    storageBucket: 'aptnote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkAnU2tByRXz3xgmT_xTLRbW6f9DW6bA',
    appId: '1:287867991282:ios:352488ab73148c73ab0c6b',
    messagingSenderId: '287867991282',
    projectId: 'aptnote',
    storageBucket: 'aptnote.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkAnU2tByRXz3xgmT_xTLRbW6f9DW6bA',
    appId: '1:287867991282:ios:352488ab73148c73ab0c6b',
    messagingSenderId: '287867991282',
    projectId: 'aptnote',
    storageBucket: 'aptnote.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );
}
